/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cloudwatch.logback;

public class App {
    public static void main(String[] args) {
        AutoLogger logger = new AutoLogger();
        logger.startExecutor();
    }
}
